#!/usr/bin/env node
var daemon = require("daemonize2").setup({
    main: "js/daemon.js",
    name: "phoenixd",
    pidfile: "phoenixd.pid"
});

switch (process.argv[2]) {
    case "start":
        daemon.start();
        break;

    case "stop":
        daemon.stop();
        break;

    default:
        console.log("Usage: [start|stop]");
}